# path to the root directory
root: /work/katsumata/BEA2019/katsumata/baselines-emnlp2016/train-2018

dir:
  moses: /work/katsumata/UMT/mosesdecoder
  moses_bin: /work/katsumata/UMT/mosesdecoder/tools
  subword_nmt: /work/katsumata/BEA2019/third_party/subword-nmt
  m2scorer: /clwork/katsumata/GEC/script/m2scorer

experiment:
  # path to working directory
  dir: ./l8.cclm.sparse.m2
  cross: true
  n: 4
  # number of parallel jobs
  jobs: 2
  threads: 16

features:
  lm: true
  wclm: true
  poslm: false
  osm: true
  esm: false
  editops: true
  levenshtein: true
  charops: true
  sparse: true
  nplm: false
  binplm: false

data:
  train_txt: <path-to>/lang8.lc.bpe.txt
  dev_orig: <path-to>/nucle.m2

  tests_m2:
    test2013: <path-to>/test2013.m2
    test2014: <path-to>/test2014.m2
    10gec: <path-to>/10gec.m2

  tests_gleu:
    jflegdev: <path-to>/jfleg.dev.src+refs.txt
    jflegtest: <path-to>/jfleg.test.src+refs.txt

  lm_path: "0:5:/cldata/cclm/cc.kenlm:8"
  wclm_path: "1:9:/cldata/cclm/cc.wclm.kenlm:8"
  wc_path: /work/katsumata/BEA2019/katsumata/cc.classes
  poslm_path:
  pos_path:

  tc_src: /work/katsumata/BEA2019/katsumata/truecase.model.bpe.src
  tc_tgt: /work/katsumata/BEA2019/katsumata/truecase.model.bpe.tgt
  bpe: /work/katsumata/BEA2019/katsumata/bpe.code.tgt.50K

  augmented_pt: false

tuning:
  # allowed values: m2, bleu, gleu
  metric: m2
  # allowed values: mert, pro, prostart, kbmirastart, bmira
  algorithm: bmira
  remert: 4
  max_it: 15
  # number of MERT parallel jobs
  jobs: 1
